name: Build and Push dev container images

on: # rebuild any PRs and main branch changes
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  build-base-images:
    name: Base Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian, bookworm, bullseye, buster, ubuntu, jammy, focal, noble, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sed
        run: |
          sed -i 's/\${TAG}/'"${{ matrix.os }}"'/g' src/base/devcontainer.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/base
          imageTag: ${{ matrix.os }}
          configFile: src/base/devcontainer.json
          push: always
  build-dev-images:
    needs: build-base-images
    name: Development Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian, bookworm, bullseye, buster, ubuntu, jammy, focal, noble, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
        stack: [bun, go, python, java, rust, ruby, php, zig, universal]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sed
        run: |
          sed -i 's/\${TAG}/'"${{ matrix.os }}"'/g' src/${{ matrix.stack }}/devcontainer.json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.stack }} dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/${{ matrix.stack }}
          imageTag: ${{ matrix.os }}
          noCache: true
          configFile: src/${{ matrix.stack }}/devcontainer.json
          push: always
