name: Build dev container image

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 1,4'

jobs:
  build:
    name: Build and Push Dev Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, debian, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/base-${{ matrix.os }}-devcontainer
          cacheFrom: ghcr.io/prulloac/base-${{ matrix.os }}-devcontainer
          configFile: src/base-${{ matrix.os }}/devcontainer.json
          push: always
      - name: Build bun dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/bun-${{ matrix.os }}-devcontainer
          cacheFrom: ghcr.io/prulloac/bun-${{ matrix.os }}-devcontainer
          configFile: src/bun-${{ matrix.os }}/devcontainer.json
          push: always