name: Test images

on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  build-base-images:
    name: Base Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [alpine, debian, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/base-${{ matrix.os }}-devcontainer
          cacheFrom: ghcr.io/prulloac/base-${{ matrix.os }}-devcontainer
          configFile: src/base-${{ matrix.os }}/devcontainer.json
          push: never
      - name: Test base ${{ matrix.os }} image
        run: |
          echo "Running tests..."
          cat src/base-${{ matrix.os }}/test.sh | docker run --rm -i ghcr.io/prulloac/base-${{ matrix.os }}-devcontainer:latest /bin/sh
  build-dev-images:
    needs: build-base-images
    name: Development Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [alpine, debian, ubuntu]
        stack: [bun, go, python, java, rust]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.stack }} dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/prulloac/${{ matrix.stack }}-${{ matrix.os }}-devcontainer
          cacheFrom: ghcr.io/prulloac/${{ matrix.stack }}-${{ matrix.os }}-devcontainer
          configFile: src/${{ matrix.stack }}-${{ matrix.os }}/devcontainer.json
          push: never
      - name: Test ${{ matrix.stack }} running on ${{ matrix.os }}
        run: |
          echo "Running tests..."
          cat src/${{ matrix.stack }}-${{ matrix.os }}/test.sh | docker run --rm -i ghcr.io/prulloac/${{ matrix.stack }}-${{ matrix.os }}-devcontainer:latest /bin/sh
